src/FS/PaysBundle/Entity/Pays.php
<?php

namespace FS\PaysBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Table(name="pays")
 * @ORM\Entity(repositoryClass="FS\PaysBundle\Entity\PaysRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *         fields={"nom"},
 *         errorPath="nom",
 *         message="This pays is already in use on that host.")
 */
class Pays
{

    /**
     * @ORM\ManyToOne(targetEntity="FS\PaysBundle\Entity\Continent",inversedBy="pays")
     * @ORM\JoinColumn(nullable=false)
     */
    public $continent;

    /**
     * @ORM\OneToOne(targetEntity="FS\PaysBundle\Entity\drapeaux", cascade={"persist", "remove"})
     */
    public $drapeaux;

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public $id;

    /**
     * @ORM\Column(name="nom", type="string", length=255 ,unique=true)
     */
    public $nom;

    /**
     * @ORM\Column(name="population", type="integer", unique=true)
     */
    public $population;

    /**
     * @ORM\Column(name="superficie", type="integer")
     */
    public $superficie;

    /**
     * @ORM\Column(name="capitale", type="string", length=255)
     */
    public $capitale;

    public  $oldPopulation ;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Pays
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set population
     *
     * @param integer $population
     *
     * @return Pays
     */
    public function setPopulation($population)
    {
        $this->population = $population;

        return $this;
    }

    /**
     * Get population
     *
     * @return integer
     */
    public function getPopulation()
    {
        return $this->population;
    }

    /**
     * Set continent
     *
     * @param \FS\PaysBundle\Entity\Continent $continent
     *
     * @return Pays
     */
    public function setContinent(\FS\PaysBundle\Entity\Continent $continent)
    {
        $this->continent = $continent;

        return $this;
    }

    /**
     * Get continent
     *
     * @return \FS\PaysBundle\Entity\Continent
     */
    public function getContinent()
    {
        return $this->continent;
    }


    /**
     * @ORM\PrePersist
     */
    public function increase()
    {
        $this->getContinent()->increaseContinent();
    }

    /**
     * @ORM\PreRemove
     */
    public function decrease()
    {
        $this->getContinent()->decreaseContinent();
    }

    /**
     * @ORM\PrePersist
     */
    public function increaseContinentPopulation()
    {
        $this->getContinent()->increasePopulation($this->population);
    }

    /**
     * @ORM\PreRemove
     */
    public function decreaseContinentPopulation(){
        $this->getContinent()->decreasePopulation($this->population);
    }

    public function getOldPopulation(){
        return $this->oldPopulation;
    }

    public  function setOldPopulation($pop){
        $this->oldPopulation = $pop;
    }
    public function setDrapeaux(drapeaux $drapeaux=null)
    {
        $this->drapeaux=$drapeaux;
    }

    /**
     * @return drapeaux
     */
    public function getDrapeaux()
    {
        return $this->drapeaux;
    }
    public function setCapitale($capitale)
    {
        $this->capitale=$capitale;
    }
    public function getCapitale()
    {
        return $this->capitale;
    }

    public function setSuperficie($superficie)
    {
        $this->superficie = $superficie;
    }

    /**
     * @return mixed
     */
    public function getSuperficie()
    {
        return $this->superficie;
    }
}

src/FS/PaysBundle/Entity/drapeaux.php
<?php


namespace FS\PaysBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Table(name="drapeaux")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */


class drapeaux
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

     /**
      * @ORM\Column(name="url", type="string", length=255)
      */
    private $url;

     /**
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
     * @var UploadedFile
     */

    public $file;

    public $tempFilename;


    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        if (null !== $this->url) {
            $this->tempFilename = $this->url;
            $this->url = null;
            $this->alt = null;
        }
    }


    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null === $this->file) {
            return;     }

        $this->url = $this->file->guessExtension();
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {

        if (null === $this->file) {
            return;
        }
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        $this->file->move(
            $this->getUploadRootDir(),
            $this->id.'.'.$this->url
        );

    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img';
    }

    public function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }

    /**

     * Get id

     *

     * @return integer

     */

    public function getId()

    {

        return $this->id;

    }

    /**
     * Set url
     * @param string $url
     * @return drapeaux
     */

    public function setUrl($url)

    {

        $this->url = $url;

        return $this;

    }

    /**

     * Get url

     *

     * @return string

     */

    public function getUrl()

    {

        return $this->url;

    }

    /**

     * Set alt

     *

     * @param string $alt

     * @return drapeaux

     */

    public function setAlt($alt)

    {

        $this->alt = $alt;

        return $this;

    }

    /**

     * Get alt

     *

     * @return string

     */

    public function getAlt()

    {

        return $this->alt;

    }

    /**

     * Get file

     *

     * @return string

     */

    public function getFile()

    {

        return $this->file;

    }

    /**

     * Set tempFilename

     *

     * @param string $tempFilename

     * @return drapeaux

     */

    public function setTempFilename($tempFilename)

    {

        $this->tempFilename = $tempFilename;

        return $this;

    }

    /**

     * Get tempFilename

     *

     * @return string

     */

    public function getTempFilename()

    {

        return $this->tempFilename;

    }

}

src/FS/PaysBundle/Form/PaysType.php
<?php

namespace FS\PaysBundle\Form;

use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\DependencyInjection\Tests\Compiler\F;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaysType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('nom')
            ->add('population')
            ->add('drapeaux', drapeauxType::class)
            ->add('capitale')
            ->add('superficie')
            ->add('continent',EntityType::class, array(
            'class' => 'FSPaysBundle:Continent',
            'choice_label' => 'nom',))
            ->add('save' ,SubmitType::class);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'FS\PaysBundle\Entity\Pays'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'fs_paysbundle_pays';
    }


}

src/FS/PaysBundle/Controller/PaysController.php
<?php
namespace FS\PaysBundle\Controller;
use FS\PaysBundle\Entity\Continent;
use FS\PaysBundle\Entity\Pays;
use FS\PaysBundle\Form\ContinentType;
use FS\PaysBundle\Form\PaysType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Doctrine\Common\EventSubscriber;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\Paginator;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


/**
 * @param Request $request
 * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
 */

class PaysController extends Controller
{
    public function indexAction($page)
    {
        if ($page < 1) {

            throw new NotFoundHttpException('Page "'.$page.'" inexistante.');
        }

        $listContinent = $this->getDoctrine()
            ->getRepository('FSPaysBundle:Pays')
            ->findAll();


        return $this->render("FSPaysBundle:Pays:index.html.twig", array(
            'listContinent' => $listContinent,
        ));
    }

    public function viewAction($id)
    {
        $pays = $this->getDoctrine()
            ->getRepository('FSPaysBundle:Pays')
            ->find($id);

        return $this->render("FSPaysBundle:Pays:view.html.twig", array(
            'pays' => $pays,
        ));
    }

    /**
     *
     * @Security("has_role('ROLE_ADMIN') and has_role('ROLE_ADMIN')")
     *
     */
    public function addAction(Request $request)
    {
        if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            // Sinon on déclenche une exception « Accès interdit »
            throw new AccessDeniedException('Accès limité aux admin.');}
        $pays = new Pays();

        // On crée le FormBuilder grâce au service form factory
        $form = $this->createForm(PaysType::class,$pays);
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($pays);
                $em->flush();

                $request->getSession()->getFlashBag()->add('success', '
Successfully registered country');
                return $this->redirectToRoute('fs_pays_countrylist');
            }
        }
        return $this->render('FSPaysBundle:Pays:add.html.twig', array('form' => $form->createView()));
    }

    public function editAction(Pays $pays,Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(PaysType::class, $pays);
        if ($request->getMethod() == 'POST') {
            $pays->setOldPopulation($pays->getPopulation());
            $form->handleRequest($request);
            var_dump($pays->getPopulation());
            if ($form->isValid()) {
                $em->flush();
                $request->getSession()->getFlashBag()->add('success', 'Successfully Modified country');
                return $this->redirectToRoute('fs_pays_countrylist');
            }
        }
        return $this->render('FSPaysBundle:Pays:edit.html.twig',
            array('form' => $form->createView(),'id'=> $pays->getId()));
    }

    public function deleteAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $req = $em->getRepository('FSPaysBundle:Pays')->find($id);

        if (!$req) {
            throw $this->createNotFoundException('No conti found for id ' . $id);
        }

        $em->remove($req);
        $em->flush();


        $request->getSession()->getFlashBag()->add('success', 'Successfully Remouved  country');
        return $this->redirectToRoute('fs_pays_countrylist');
    }



    public function countrylistAction(Request $request)
    {
         $em=$this->getDoctrine()->getManager();
        $ListPays = $em->getRepository('FSPaysBundle:Pays')
            ->findAll();

        $paginator  = $this->get("knp_paginator");
        $result=$paginator->paginate(
            $ListPays,
            $request->query->getInt('page',1),
            $request->query->getInt('limit',5));

        return $this->render("FSPaysBundle:Pays:countrylis.html.twig", array(
            'ListPays' => $result,
        ));
    }

        }

src/FS/PaysBundle/Resources/views/Pays/add.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/add.html.twig #}

{% extends "FSPaysBundle::layout.html.twig" %}

{% block body %}
    <h1>Add Country </h1>

    {{ include("FSPaysBundle:Pays:form.html.twig") }}



{% endblock %}

src/FS/PaysBundle/Resources/views/Pays/countrylis.html.twig
{% extends "FSPaysBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block fspays_body %}
    <div class="panel-heading">
    <div class="panel-title">
        <div class="row">
            <div class="col-md-6">
                <h1>
                Country List
 </h1>
            </div>
            {% if is_granted('ROLE_ADMIN') %}
            <div class="col-md-12">
                <a href="{{ path('fs_pays_addcountry') }}" class="btn btn-primary pull-right"> ADD COUNTRY</a></div>


    </div>
        {% endif %}

        <div class="panel-body">

            <table class="table table-striped" id="dataTables-example">
                <thead>
                <th>#</th>
                <th>Nom</th>
                <th>Population</th>
                <th>Continent</th>
                <th>Capitale</th>
                <th>superficie</th>
                <th>Actions</th>
                </thead>
                <tbody>
                {% for pays in ListPays %}
                    <tr class="{% if loop.index is divisibleby(2) %}odd{% else %}even{% endif %}">
                        <td> <img
                                    src="{{ asset(pays.drapeaux.webPath) }}"
                                    alt="{{ pays.drapeaux.alt }}"
                            /></td>
                        <td col>{{ pays.nom }}</td>
                        <td>{{ pays.population }}</td>
                        <td>{{ pays.continent.nom }}</td>
                        <td>{{ pays.capitale }}</td>
                        <td>{{ pays.superficie }}</td>
                         <td>
                            <a href="{{ path('fs_pays_editcountry',{id : pays.id}) }}"> <p class="fa fa-edit"></p></a>
                             {% if is_granted('ROLE_ADMIN') %}
                            <a data-confirm="Etes-vous certain de vouloir supprimer?" href="{{ path('fs_pays_deletecountry',{id : pays.id}) }}"><p class="glyphicon glyphicon-remove"> </p></a>
                       {% endif %}
                        </td>
                    </tr>

                {% else %}
                    <tr>
                        <td>Pas (encore !) pays enregistrée</td>
                    </tr>
                {% endfor%}
                </tbody>
            </table>
        </div>
    </div>
      </div>
{% endblock %}

src/FS/PaysBundle/Resources/views/Pays/edit.html.twig
{% extends "FSPaysBundle::layout.html.twig" %}

{% block title %}
    Modification - {{ parent() }}
{% endblock %}

{% block fspays_body %}

    <h1>Edit Country </h1>

    {{ include("FSPaysBundle:Pays:form.html.twig") }}





{% endblock %}

src/FS/PaysBundle/Resources/views/Pays/form.html.twig
    <div class="panel-heading">
        <div class="panel-title">
        <div class="row">


        </div>
    </div>
<hr>

        <div class="panel-body">
                <span class="pull-center">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}

    {# Génération du label + error + widget pour un champ. #}


    {# Génération manuelle et éclatée : #}
    <div class="form-group">
        {# Génération du label. #}
        {{ form_label(form.nom, "NAME", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {# Affichage des erreurs pour ce champ précis. #}
        {{ form_errors(form.nom) }}
        <div class="col-sm-10">
            {# Génération de l'input. #}
            {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>
    {# Idem pour un autre champ. #}
    <div class="form-group">
        {{ form_label(form.population, "POPULATION", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.population) }}
        <div class="col-sm-10">
            {{ form_widget(form.population, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.continent, "CONTIENET", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.continent) }}
        <div class="col-sm-10">
            {{ form_widget(form.continent, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.drapeaux, "DRAPEAUX", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.drapeaux) }}
        <div class="col-sm-10">
            {{ form_widget(form.drapeaux, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.capitale, "CAPITALE", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.capitale) }}
        <div class="col-sm-10">
            {{ form_widget(form.capitale, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.superficie, "SUPERFICIE", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        {{ form_errors(form.superficie) }}
        <div class="col-sm-10">
            {{ form_widget(form.superficie, {'attr': {'class': 'form-control'}}) }}
        </div>
    </div>
    {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
    {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

    {# Génération automatique des champs pas encore écrits.
       Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
       et tous les champs cachés (type « hidden »). #}
    {{ form_rest(form) }}

    {# Fermeture de la balise <form> du formulaire HTML #}
    {{ form_end(form) }}
 </span>

            <div class="clearfix"></div>
        </div>
    </a>
</div>

src/FS/PaysBundle/Resources/views/Pays/menu.html.twig
<ul class="nav nav-pills nav-stacked">

</ul>

src/FS/PaysBundle/Resources/views/Pays/view.html.twig
{% extends "FSPaysBundle::layout.html.twig" %}

{% block title %}
    Détaille de pays - {{ parent() }}
{% endblock %}

{% block fspays_body %}
    <h2>Bravoo !!!</h2>
    <h3>  Pays {{ pays.nom }}</h3>
    qui a comme population
    {{ pays.population }}, et {{ pays.continent.nom }} pays a été ajoutée avec succée!!!!

    <p>
        <a href="{{ path('fs_pays_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
        <a href="{{ path('fs_pays_editcountry', {'id': pays.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier
        </a>
        <a href="{{ path('fs_pays_deletecountry', {'id': pays.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer
        </a>
    </p>

{% endblock %}